version: '3.8'

services:
  groupbudget.webapi:
    image: ${DOCKER_REGISTRY-}groupbudgetwebapi
    build:
      context: .
      dockerfile: GroupBudget.WebApi/Dockerfile
    ports:
      - "30000:80"
      - "30001:443"
    volumes:
      - "E:/Temp/GroupBudget/Logs:/app/logs"

  mongo:
    image: mongo
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "30002:8081"
  eventstore.db:
    image: eventstore/eventstore
    command: --enable-external-tcp --enable-atom-pub-over-http --run-projections=all --start-standard-projections=true
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_INT_TCP_PORT=1112
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_INT_HTTP_PORT=2112
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
    restart: always
    ports:
      - "31112:1112"
      - "31113:1113"
      - "32112:2112"
      - "32113:2113"
  seq:
    image: datalust/seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "30003:80"